services:
  od-official-server:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1G
    cpus: '2'
    ports: 
      - "127.0.0.1:1313:1313"
    environment:
      - SALT_ENCRYPTION_KEY
      - SALT_ENCRYPTION_IV
      - SCYLLA_CASSANDRA_PASSWORD
      - SCYLLA_DB_USER
      - API_PORT=1313
